-- MySQL Script generated by MySQL Workbench
-- 09/11/16 23:18:34
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema coavalieitor_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema coavalieitor_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `coavalieitor_db` DEFAULT CHARACTER SET utf8 ;
USE `coavalieitor_db` ;

-- -----------------------------------------------------
-- Table `coavalieitor_db`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coavalieitor_db`.`usuario` ;

CREATE TABLE IF NOT EXISTS `coavalieitor_db`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(255) NOT NULL,
  `senha` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coavalieitor_db`.`professor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coavalieitor_db`.`professor` ;

CREATE TABLE IF NOT EXISTS `coavalieitor_db`.`professor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_professor_usuario_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_professor_usuario`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `coavalieitor_db`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `coavalieitor_db`.`aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `coavalieitor_db`.`aluno` ;

CREATE TABLE IF NOT EXISTS `coavalieitor_db`.`aluno` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(255) NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`, `usuario_id`),
  INDEX `fk_aluno_usuario1_idx` (`usuario_id` ASC),
  CONSTRAINT `fk_aluno_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `coavalieitor_db`.`usuario` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
